config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords]
  root to: 'homes#top'
  get 'about' => 'homes#about'

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resources :tweets, only: [:show, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :replies, only: [:create, :destroy]
    end
    resources :study_times, only: [:create, :destroy, :edit, :update]
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :topics, only: [:index, :show, :create, :new] do
    resources :comments, only: [:create]
  end
  get 'search' => 'searches#search'
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many_attached :images
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 500 }

  # トピックの並び順をソートするクラスメソッド
  def self.sort(selection)
    if selection == 'new'
      Topic.order(created_at: :DESC) # 作成日が新しい順
    elsif selection == 'old'
      Topic.order(created_at: :ASC) # 作成日が古い順
    elsif selection == 'many'
      Topic.find(Comment.group(:topic_id).order(Arel.sql('count(topic_id) desc')).pluck(:topic_id)) # コメントが多い順
    else
      Topic.find(Comment.group(:topic_id).order(Arel.sql('count(topic_id) asc')).pluck(:topic_id)) # コメントが少ない順
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def new
    @topic = Topic.new
  end

  def show
    @topic = Topic.find(params[:id])
    @comments = @topic.comments.page(params[:page])
    @comment = Comment.new
  end

  def index
    @current_user = current_user
    if selection = params[:keyword]
      @topics = Topic.sort(selection)
      @topics = Kaminari.paginate_array(@topics).page(params[:page])
    else
      @topics = Topic.page(params[:page]).reverse_order
    end
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to topic_path(@topic)
    else
      flash.now[:error] = 'トピックの投稿に失敗しました。'
      render "new"
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :body, images: [])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/index.html.slim
.col-lg-6.p-md-4.p-3.mx-auto.shadow-lg.rounded
  ul.nav.nav-tabs.nav-justified.nav-pills.mb-3.border-0
    li.nav-item
      = link_to root_path, class: 'nav-link text-dark bg-light border' do
        i.fas.fa-house
    li.nav-item
      = link_to topics_path, class: 'nav-link active text-light' do
        i.fas.fa-chalkboard
    li.nav-item
      = link_to users_path, class: 'nav-link text-dark bg-light border' do
        i.fas.fa-crown
  .p-2.shadow-sm.bg-light.border.rounded
    span.title.font-weight-bold
      i.fas.fa-chalkboard.mx-3
      | トピック一覧
  .row.no-gutters.py-3.border-bottom.align-items-md-center
    .create-btn.mb-2.mb-md-0.col-12.col-md-auto
      = link_to 'トピックを作成する', new_topic_path, class: "btn post btn-sm px-3 rounded-pill text-white font-weight-bold"
    .form-inline.ml-md-auto.col-12.col-md-auto
      = form_with url: topics_path, method: :get, local: true do |f|
        .input-group
          .input-group-prepend
            = f.select :keyword, [ ['作成日が新しい順', 'new'],
                                   ['作成日が古い順', 'old'],
                                   ['コメントが多い順', 'many'],
                                   ['コメントが少ない順', 'less'],
                                 ], {}, class: 'btn btn-light border'
          .input-group-append
            = button_tag :type => "submit", :class =>"btn btn-dark" do
              i.fa.fa-sort
  .topics-area
    - @topics.each do |topic|
      .topic.border-bottom.py-3
        .index
          .topic-title
            = link_to topic_path(topic) do
              = topic.title
              | （
              = topic.comments.count
              | ）
          .time
            = topic.created_at.strftime('%Y/%m/%d　%H:%M:%S')
    = paginate @topics

app/views/topics/new.html.slim
.col-lg-5.p-md-4.p-3.mx-auto.shadow-lg.rounded
  .border.rounded.p-2.bg-light.mb-3.text-center.shadow-sm
    span.title.font-weight-bold
      | 新規トピック作成
  = render 'layouts/error_messages', model: @topic
  = form_with model:@topic, local:true do |f|
    .form-group
      = f.label :トピックタイトル
      = f.text_field :title, autofocus: true, placeholder:"50文字以内で入力してください", class: 'form-control bg-light'
    .form-group
      = f.label :コメント
      = f.text_area :body, placeholder:"500文字以内で入力してください", rows: '15', class: 'form-control bg-light'
    .form-group
      = f.file_field :images, multiple: true, class: 'form-control-file'
    .form-group.text-center
      = f.submit "トピックを作成", class: 'btn post rounded-pill text-white font-weight-bold col-md-4 col-6'

app/views/topics/show.html.slim
.col-lg-6.p-md-4.p-3.mx-auto.shadow-lg.rounded
  .border-bottom.pb-3
    span.title.font-weight-bold
      = @topic.title
  .topic.py-4.border-bottom
    .head-area
      = link_to user_path(@topic.user), class: "text-success" do
        - if @topic.user.image.attached?
          = image_tag @topic.user.image.variant(resize:'50x50'), class: 'rounded-circle mr-3'
        - else
          = image_tag 'no-image-icon.jpg', size: '50x50', class: 'rounded-circle border mr-3'
        span.font-weight-bold
          = @topic.user.name
    .body-show-area.py-3
      = safe_join(@topic.body.split("\n"),tag(:br))
      - if @topic.images.attached?
        .images.d-flex.flex-wrap.justify-content-center.py-4
          - @topic.images.each do |image|
            .image
              = image_tag image.variant(resize: '300').processed, class: 'shadow'
    .foot-area
      span.mr-5
        i.far.fa-comment.mr-1
        = @topic.comments.count
      = @topic.created_at.strftime('%Y/%m/%d　%H:%M:%S')
  .border-bottom.py-3
    span.title.font-weight-bold
      = @topic.comments.count
      | 件のコメント
  .comments-area.mb-4
    - @comments.each.with_index(@comments.offset_value + 1) do |comment, i|
      .comment.border-bottom.py-3
        .head-area.mb-3
          span.mr-3
            | No.
            = i
          = link_to comment.user.name, user_path(comment.user), class: "text-success font-weight-bold"
        .body-area.mb-3
          p
            = safe_join(comment.body.split("\n"),tag(:br))
          - if comment.images.attached?
            .images.d-flex.flex-wrap.justify-content-center
              - comment.images.each do |image|
                .image
                  = image_tag image.variant(resize: '200').processed, class: 'shadow'
        .foot-area
          span
            = comment.created_at.strftime('%Y/%m/%d　%H:%M:%S')
    = paginate @comments
  .comment-form-area
    = form_with model:[@topic, @comment], local:true do |f|
      .form-group
        = f.label :自由にコメントを投稿してみましょう！（荒らし行為や連投はご遠慮ください）
        = f.text_area :body, class: 'form-control bg-light', rows: '10', placeholder: '500字以内でコメントしてみよう！'
      .form-group
        = f.file_field :images, multiple: true, class: 'form-control-file'
      .form-group.text-center
        = f.submit "コメントする", class: 'btn post rounded-pill text-white font-weight-bold col-md-4 col-6'