config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords]
  root to: 'homes#top'
  get 'about' => 'homes#about'

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resources :tweets, only: [:show, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :replies, only: [:create, :destroy]
    end
    resources :study_times, only: [:create, :destroy, :edit, :update]
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :topics, only: [:index, :show, :create, :new] do
    resources :comments, only: [:create]
  end
  get 'search' => 'searches#search'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many_attached :images
  validates :body, presence: true, length: { maximum: 140 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 部分一致で検索するクラスメソッド
  def self.search_for(content)
    Tweet.where('body LIKE ?', '%' + content + '%')
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :ensure_correct_user, only: [:destroy]

  def show
    @tweet = Tweet.find(params[:id])
    @replies = @tweet.replies.page(params[:page])
    @count = @tweet.replies.count
    @reply = Reply.new
    @user = @tweet.user
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to user_tweet_path(current_user, @tweet)
    else
      @tweets = Tweet.where(user_id: [current_user.id, *current_user.following_ids]).page(params[:page]).reverse_order
      @tweet_new = Tweet.new
      flash.now[:error] = 'つぶやきの投稿に失敗しました。'
      render "homes/top"
    end
  end

  def destroy
    @tweet.destroy
    redirect_to root_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body, images: [])
  end

  def ensure_correct_user
    @tweet = Tweet.find(params[:id])
    unless @tweet.user == current_user
      redirect_to root_path
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_index.html.slim
- tweets.each do |tweet|
  .tweet.border-bottom.py-3 id="tweet_#{tweet.id}"
    .head-area
      = link_to user_path(tweet.user), class: "text-dark" do
        - if tweet.user.image.attached?
          = image_tag tweet.user.image.variant(resize:'50x50'), class: 'rounded-circle mr-3'
        - else
          = image_tag 'no-image-icon.jpg', size: '50x50', class: 'rounded-circle border mr-3'
        span.font-weight-bold
          = tweet.user.name
    .body-area.mt-3
      = link_to user_tweet_path(tweet.user, tweet), class: 'text-dark' do
        = simple_format(tweet.body)
        - if tweet.images.attached?
          .images.d-flex.flex-wrap.justify-content-center.mb-3
            - tweet.images.each do |image|
              .image
                = image_tag image.variant(resize: '150').processed, class: 'shadow'
    .count-area.mb-2
      span.mr-5
        = render "favorites/favorite-btn", tweet: tweet
      span
        i.far.fa-comment.mr-1
        = tweet.replies.count
    .foot-area.d-flex.align-items-end
      .time
        = tweet.created_at.strftime('%Y/%m/%d　%H:%M:%S')
      - if tweet.user == current_user
        .delete-btn.ml-auto
          = link_to 'つぶやきを削除', user_tweet_path(tweet.user, tweet), method: :delete, class: "btn btn-sm btn-outline-danger px-3 font-weight-bold rounded-pill"
= paginate tweets

app/views/tweets/_tweet-form.html.slim
.tweet-form-area.border-bottom.border-top.py-4.text-center
  button.btn.post.rounded-pill.text-white.font-weight-bold.col-md-4.col-6[type="button" data-toggle="modal" data-target="#modal1"]
    | つぶやく
  #modal1.modal.fade[tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true"]
    .modal-dialog[role="document"]
      .modal-content
        .modal-header
          h6#label1.modal-title
            | いまどうしてる？
          button.close[type="button" data-dismiss="modal" aria-label="Close"]
            span[aria-hidden="true"]
              | ×
        .modal-body
          = form_with model:[user,tweet], local:true do |f|
            .form-group
              = f.text_area :body, class: 'form-control bg-light', rows: '10', placeholder: '140字以内でつぶやこう！'
            .form-group
              = f.file_field :images, multiple: true, class: 'form-control-file'
            .form-group.text-center
              = f.submit "つぶやく", class: 'btn post rounded-pill text-white font-weight-bold col-md-4 col-6'

app/views/tweets/show.html.slim
.col-lg-6.p-md-4.p-3.mx-auto.shadow-lg.rounded
  .tweet.pb-4 id="tweet_#{@tweet.id}" 
    .head-area
      = link_to user_path(@tweet.user), class: "text-dark" do
        - if @tweet.user.image.attached?
          = image_tag @tweet.user.image.variant(resize:'50x50'), class: 'rounded-circle mr-3'
        - else
          = image_tag 'no-image-icon.jpg', size: '50x50', class: 'rounded-circle border mr-3'
        span.font-weight-bold
          = @tweet.user.name
    .body-show-area.mt-3
      = simple_format(@tweet.body)
      - if @tweet.images.attached?
        .images.d-flex.flex-wrap.justify-content-center.mb-3
          - @tweet.images.each do |image|
            .image
              = image_tag image.variant(resize: '300').processed, class: 'shadow'
    .count-area.mb-2
      span.mr-5
        = render "favorites/favorite-btn", tweet: @tweet
      span
        i.far.fa-comment.mr-1
        = @tweet.replies.count
    .foot-area.d-flex.align-items-end
      .time
        = @tweet.created_at.strftime('%Y/%m/%d　%H:%M:%S')
      - if @tweet.user == current_user
        .delete-btn.ml-auto
          = link_to 'つぶやきを削除', user_tweet_path(@tweet.user, @tweet), method: :delete, class: "btn btn-sm btn-outline-danger px-3 font-weight-bold rounded-pill"
  .reply-area.mb-4
    .border-top.border-bottom.py-3
      span.title.font-weight-bold
        = @count
        | 件の返信
    .replies-area
      - @replies.each do |reply|
        .reply.border-bottom.py-3
          .head-area
            = link_to user_path(reply.user), class: "text-dark" do
              - if reply.user.image.attached?
                = image_tag reply.user.image.variant(resize:'50x50'), class: 'rounded-circle mr-3'
              - else
                = image_tag 'no-image-icon.jpg', size: '50x50', class: 'rounded-circle border mr-3'
              span.font-weight-bold
                = reply.user.name
          .body-area.mt-3
            = simple_format(reply.body)
            - if reply.images.attached?
              .images.d-flex.flex-wrap.justify-content-center.mb-3
                - reply.images.each do |image|
                  .image
                    = image_tag image.variant(resize: '150').processed, class: 'shadow'
          .foot-area.d-flex.align-items-end
            .time
              = reply.created_at.strftime('%Y/%m/%d　%H:%M:%S')
            - if reply.user == current_user
              .delete-btn.ml-auto
                = link_to '返信を削除', user_tweet_reply_path(@tweet.user, @tweet, reply), method: :delete, class: "btn btn-sm btn-outline-danger px-3 font-weight-bold rounded-pill"
      = paginate @replies
  .reply-form-area
    = form_with model:[@user, @tweet, @reply], local:true do |f|
      .form-group
        = f.label :このつぶやきについてどう思いましたか？
        = f.text_area :body, class: 'form-control rounded bg-light', rows: '7', placeholder: '140字以内で返信してみよう！'
      .form-group
        = f.file_field :images, multiple: true, class: 'form-control-file'
      .form-group.text-center
        = f.submit "返信する", class: 'btn post rounded-pill text-white px-4 font-weight-bold col-md-4 col-6'