config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords]
  root to: 'homes#top'
  get 'about' => 'homes#about'

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resources :tweets, only: [:show, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :replies, only: [:create, :destroy]
    end
    resources :study_times, only: [:create, :destroy, :edit, :update]
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :topics, only: [:index, :show, :create, :new] do
    resources :comments, only: [:create]
  end
  get 'search' => 'searches#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #ゲストログインのクラスメソッド
  def self.guest
    find_or_create_by!(name: 'ゲストユーザー' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :topics
  has_many :comments
  has_many :study_times
  has_one_attached :image

  validates :name, length: { minimum: 1, maximum: 10 }, uniqueness: true
  validates :introduction, length: { maximum: 200 }

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  # 直近一週間の勉強時間の合計を算出するインスタンスメソッド
  def last7_time
    array = []
    study_times.last(7).each do |study_time|
      array << study_time.time
    end
    array.sum.round(1)
  end

  # 一週間（月〜金）の勉強時間の合計を算出するインスタンスメソッド
  def weekly_time
    array = []
    study_times.where(study_times: { created_at: Time.current.all_week }).each do |study_time|
      array << study_time.time
    end
    array.sum.round(1)
  end

  # トータルの勉強時間の合計を算出するインスタンスメソッド
  def total_time
    study_times.sum(:time).round(1)
  end

  # 一週間（月〜金）の勉強時間が多い順でレコードを10件取得するクラスメソッド
  def self.weekly_time
    User.find(StudyTime.group(:user_id).where(study_times: { created_at: Time.current.all_week }).order(Arel.sql('sum(time) desc')).limit(10).pluck(:user_id))
  end

  # 部分一致で検索するクラスメソッド
  def self.search_for(content)
    User.where('name LIKE ?', '%' + content + '%')
  end

  # 勉強時間ランキングの対象期間（週間、トータル）を判別するクラスメソッド
  def self.sort(selection)
    if selection == 'weekly'
      User.find(StudyTime.group(:user_id).where(study_times: { created_at: Time.current.all_week }).order(Arel.sql('sum(time) desc')).limit(10).pluck(:user_id))
    else
      User.find(StudyTime.group(:user_id).order(Arel.sql('sum(time) desc')).limit(10).pluck(:user_id))
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'ゲストユーザーでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.page(params[:page]).reverse_order
    @study_time = StudyTime.new
    @last7_time = @user.last7_time
    @total_time = @user.total_time
  end

  def index
    if @selection = params[:keyword]
      @users = User.sort(@selection)
      @users = Kaminari.paginate_array(@users).page(params[:page])
    else
      @users = User.weekly_time
      @users = Kaminari.paginate_array(@users).page(params[:page])
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash.now[:error] = 'プロフィールの編集に失敗しました。'
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "ゲストユーザー"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.slim
- users.each do |user|
  .user.border-bottom.pt-3
    .head-area.d-flex.align-items-center
      .image.mr-3
        = link_to user_path(user) do
          - if user.image.attached?
            = image_tag user.image.variant(resize:'50x50'), class: 'rounded-circle'
          - else
            = image_tag 'no-image-icon.jpg', size: '50x50', class: 'rounded-circle border'
      .name-area.d-md-flex.align-items-center
        .name.font-weight-bold.mr-md-4
          = link_to user.name, user_path(user), class: "text-dark"
        .button.ml-md-4.mt-2.mt-md-0
          - if current_user.name == "ゲストユーザー"
          - else
            - if current_user.following?(user)
              = link_to "フォロー中", user_relationships_path(user), method: :delete, class: "btn btn-sm btn-outline-secondary px-3 rounded-pill font-weight-bold"
            - else
              = link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-sm btn-dark px-3 rounded-pill font-weight-bold"
    .body.pt-3
      = simple_format(user.introduction)
= paginate users

app/views/users/edit.html.slim
.col-lg-5.p-md-4.p-3.mx-auto.shadow-lg.rounded
  .border.rounded.p-2.bg-light.mb-3.text-center.shadow-sm
    span.title.font-weight-bold
      | プロフィール編集
  = render 'layouts/error_messages', model: @user
  = form_with model:@user, local:true do |f|
    .form-group
      = f.label :ユーザーアイコン
      .image-group
        - if @user.image.attached?
          = image_tag @user.image.variant(resize:'100x100')
        - else
          = image_tag 'no_image.jpg', size: '100x100', class: 'border'
    .form-group.mb-4
      = f.file_field :image, class: 'form-control-file'
    .form-group
      = f.label :ハンドルネーム
      = f.text_field :name, autofocus: true, placeholder:"1〜10文字以内で入力してください", class: 'form-control bg-light'
    .form-group
      = f.label :自己紹介文
      = f.text_area :introduction, placeholder:"200文字以内で入力してください", rows: '10', class: 'form-control bg-light'
    .form-group.text-center
      = f.submit "変更を保存", class: 'btn post rounded-pill text-white font-weight-bold col-md-4 col-6'

app/views/users/index.html.slim
.col-lg-6.p-md-4.p-3.mx-auto.shadow-lg.rounded
  ul.nav.nav-tabs.nav-justified.nav-pills.mb-3.border-0
    li.nav-item
      = link_to root_path, class: 'nav-link text-dark bg-light border' do
        span.fas.fa-house
    li.nav-item
      = link_to topics_path, class: 'nav-link text-dark bg-light border' do
        span.fas.fa-chalkboard
    li.nav-item
      = link_to users_path, class: 'nav-link active text-light' do
        span.fas.fa-crown
  .border.rounded.p-2.bg-light.shadow-sm
    span.title.font-weight-bold
      i.fas.fa-crown.mx-3
      - if @selection == 'total'
        |  トータルＴＯＰ１０
      - else
        |  週間ＴＯＰ１０
  .row.no-gutters.py-3.border-bottom.align-items-md-center
    - if @selection == 'total'
    - else
      .note.mb-2.mb-md-0
        span
          | 毎週月曜0時リセット
    .form-inline.ml-md-auto
      = form_with url: users_path, method: :get, local: true do |f|
        .input-group
          .input-group-prepend
            = f.select :keyword, [ ['週間勉強時間ランキング', 'weekly'],
                                   ['トータル勉強時間ランキング', 'total'],
                                 ], {}, class: 'btn btn-light border'
          .input-group-append
            = button_tag :type => "submit", :class =>"btn btn-dark" do
              i.fa.fa-sort
  .rank-area
    - @users.each.with_index(@users.offset_value + 1) do |user, i|
      .user.border-bottom.py-3
        .d-md-flex
          .d-flex.align-items-center.mb-3.mb-md-0
            .index.mr-4
              = i
            .image.mr-3
              = link_to user_path(user) do
                - if user.image.attached?
                  = image_tag user.image.variant(resize:'50x50'), class: 'rounded-circle'
                - else
                  = image_tag 'no-image-icon.jpg', size: '50x50', class: 'rounded-circle border'
            .name.font-weight-bold
              = link_to user.name, user_path(user), class: "text-dark"
          .d-flex.ml-auto.align-items-center
            - if @selection == 'total'
              .total_time.h5.m-0.mr-4
                = user.total_time
                |  時間
              .weekly_time
                |  週間 
                = user.weekly_time
                |  時間
            - else
              .weekly_time.h5.m-0.mr-4
                = user.weekly_time
                |  時間
              .total_time
                | トータル 
                = user.total_time
                |  時間

app/views/users/show.html.slim
.col-lg-6.p-md-4.p-3.mx-auto.shadow-lg.rounded
  .user.border-bottom
    .head-area.d-flex.align-items-lg-center.align-items-end
      .image.mr-4
        - if @user.image.attached?
          = image_tag @user.image.variant(resize:'80x80'), class: 'rounded-circle'
        - else
          = image_tag 'no_image.jpg', size: '80x80', class: 'rounded-circle border'
      .name-area.d-lg-flex.align-items-end
        .name.font-weight-bold.h5.mr-lg-5.m-lg-0
          = @user.name
        .button
          - if !(@user.name == "ゲストユーザー") && @user == current_user
            = link_to 'プロフィールを編集', edit_user_path(@user), class: "btn btn-sm btn-outline-dark px-3 rounded-pill font-weight-bold"
          - elsif current_user.name == "ゲストユーザー"
          - else
            - if current_user.following?(@user)
              = link_to "フォロー中", user_relationships_path(@user), method: :delete, class: "btn btn-sm btn-outline-secondary px-3 rounded-pill"
            - else
              = link_to "フォローする", user_relationships_path(@user), method: :post, class: "btn btn-sm btn-dark px-3 rounded-pill"
    .follow-area.my-3
      span.mr-4
        = link_to user_followings_path(@user), class: 'text-dark' do
          = @user.followings.count
          |  フォロー中
      span
        = link_to user_followers_path(@user), class: 'text-dark' do
          = @user.followers.count
          |  フォロワー
    .body-area
      = simple_format(@user.introduction)
  .study_time-area.mb-4.py-4.border-bottom
    .weekly-time.h5.font-weight-bold
      | 最新7件の勉強時間計： 
      = @last7_time
      |  時間
    .total-time
      | トータル勉強時間： 
      = @total_time
      |  時間
    .card-group.my-4
      - @user.study_times.last(7).each do |study_time|
        .card.text-center
          .card-header.p-2
            span
              = study_time.created_at.strftime('%m/%d')
          .card-body.p-2
            span
              = study_time.time.round(1)
              |  h
            - if @user == current_user
              .delete-btn.mt-3
                = link_to '編集', edit_user_study_time_path(@user, study_time), class: 'btn post rounded text-white btn-sm mb-2 px-3 font-weight-bold'
              .edit-btn
                = link_to '削除', user_study_time_path(@user, study_time), method: :delete, class: "btn btn-sm btn-outline-danger px-3 mb-2 font-weight-bold rounded"
    - if @user == current_user
      .note
        | 本日の勉強時間を記録しましょう！（原則として一日一回、小数点第一位まで入力可）
      .form-area.ml-3.pt-3
        = form_with model:[@user,@study_time], local:true do |f|
          = f.number_field :time, step: '0.1', min: 0, max: 24, class: 'border rounded mr-2 bg-light'
          | 時間
          = f.submit "記録する", class: 'btn btn-sm post rounded-pill text-white ml-5 font-weight-bold col-md-3 col-4'
  .border.rounded.p-2.bg-light.shadow-sm
    span.title.font-weight-bold
      i.fas.fa-comments.mx-3
      | つぶやき
  = render 'tweets/index', tweets: @tweets