config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords]
  root to: 'homes#top'
  get 'about' => 'homes#about'

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resources :tweets, only: [:show, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :replies, only: [:create, :destroy]
    end
    resources :study_times, only: [:create, :destroy, :edit, :update]
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :topics, only: [:index, :show, :create, :new] do
    resources :comments, only: [:create]
  end
  get 'search' => 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_many_attached :images
  validates :body, presence: true, length: { maximum: 500 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  has_many_attached :images
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/study_time.rb
class StudyTime < ApplicationRecord
  belongs_to :user
  validates :time, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many_attached :images
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 500 }

  # トピックの並び順をソートするクラスメソッド
  def self.sort(selection)
    if selection == 'new'
      Topic.order(created_at: :DESC) # 作成日が新しい順
    elsif selection == 'old'
      Topic.order(created_at: :ASC) # 作成日が古い順
    elsif selection == 'many'
      Topic.find(Comment.group(:topic_id).order(Arel.sql('count(topic_id) desc')).pluck(:topic_id)) # コメントが多い順
    else
      Topic.find(Comment.group(:topic_id).order(Arel.sql('count(topic_id) asc')).pluck(:topic_id)) # コメントが少ない順
    end
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many_attached :images
  validates :body, presence: true, length: { maximum: 140 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 部分一致で検索するクラスメソッド
  def self.search_for(content)
    Tweet.where('body LIKE ?', '%' + content + '%')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #ゲストログインのクラスメソッド
  def self.guest
    find_or_create_by!(name: 'ゲストユーザー' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :topics
  has_many :comments
  has_many :study_times
  has_one_attached :image

  validates :name, length: { minimum: 1, maximum: 10 }, uniqueness: true
  validates :introduction, length: { maximum: 200 }

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  # 直近一週間の勉強時間の合計を算出するインスタンスメソッド
  def last7_time
    array = []
    study_times.last(7).each do |study_time|
      array << study_time.time
    end
    array.sum.round(1)
  end

  # 一週間（月〜金）の勉強時間の合計を算出するインスタンスメソッド
  def weekly_time
    array = []
    study_times.where(study_times: { created_at: Time.current.all_week }).each do |study_time|
      array << study_time.time
    end
    array.sum.round(1)
  end

  # トータルの勉強時間の合計を算出するインスタンスメソッド
  def total_time
    study_times.sum(:time).round(1)
  end

  # 一週間（月〜金）の勉強時間が多い順でレコードを10件取得するクラスメソッド
  def self.weekly_time
    User.find(StudyTime.group(:user_id).where(study_times: { created_at: Time.current.all_week }).order(Arel.sql('sum(time) desc')).limit(10).pluck(:user_id))
  end

  # 部分一致で検索するクラスメソッド
  def self.search_for(content)
    User.where('name LIKE ?', '%' + content + '%')
  end

  # 勉強時間ランキングの対象期間（週間、トータル）を判別するクラスメソッド
  def self.sort(selection)
    if selection == 'weekly'
      User.find(StudyTime.group(:user_id).where(study_times: { created_at: Time.current.all_week }).order(Arel.sql('sum(time) desc')).limit(10).pluck(:user_id))
    else
      User.find(StudyTime.group(:user_id).order(Arel.sql('sum(time) desc')).limit(10).pluck(:user_id))
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, except: [:about]
  def top
    # whereメソッドでログインユーザーとそのフォローしているユーザーのつぶやきを取得する
    # "*"は可変長引数で、複数の引数（フォローしているユーザーID）を配列として返すことができる
    # reverse_orderメソッドで作成日降順（新着順）に取得つぶやきをソートする
    @tweets = Tweet.where(user_id: [current_user.id, *current_user.following_ids]).page(params[:page]).reverse_order
    @tweet_new = Tweet.new
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_alert(key)
    case key
    when "alert"
      "warning"
    when "notice"
      "success"
    when "error"
      "danger"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/study_times_helper.rb
module StudyTimesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.slim
- if model.errors.any?
  .alert.alert-warning
    ul
      - model.errors.full_messages.each do |message|
        li
          = message

app/views/layouts/_flash_messages.html.slim
 - flash.each do |key, value|
  div class=("alert alert-#{bootstrap_alert(key)} alert-dismissible") 
    span
      = value
    button.close[type="button" data-dismiss="alert" aria-label="Close"]
      span[aria-hidden="true"]
        | ×

app/views/layouts/_footer.html.slim
footer.bg-dark.text-white.pt-5.pb-4
  .container
    .row.no-gutters
      .col-lg-4.col-sm-6
        p
          | 駆け出しエンジニア同士で高めあえるSNS
        = image_tag 'logo.png', height: '40px'
      .col-lg-4.col-sm-6
        h6.mb-3.mt-3.mt-sm-0
          | Link
        ul.m-0.list-unstyled.text-white-50
          li
            | 運営者情報
          li
            | プライバシーポリシー
    .right.text-center.mt-3
      span
        | © 2021 ShotaTakahashi

app/views/layouts/_header.html.slim
header.sticky-top.shadow-sm
  nav.navbar.navbar-expand-xl.navbar-light
    a.navbar-brand.logo.ml-xl-5[href="/"]
      = image_tag 'logo.png', height: '50px'
    button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    #navbarNavDropdown.collapse.navbar-collapse
      - if user_signed_in?
          ul.navbar-nav.ml-xl-5.align-items-xl-center.align-items-start
            li.nav-item.mr-xl-4
              = link_to user_path(current_user.id), class: 'nav-link text-light' do
                - if current_user.image.attached?
                  = image_tag current_user.image.variant(resize:'35x35'), class: 'image rounded-circle mr-1'
                - else
                  = image_tag 'no-image-icon.jpg', size: '35x35', class: 'image rounded-circle mr-1'
                span.font-weight-bold
                  = current_user.name
            li.nav-item.dropdown.mr-xl-4
              a#dropdown1.btn.dropdown-toggle.nav-link.text-light[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
                | コンテンツ
              .dropdown-menu[aria-labelledby="dropdown1"]
                = link_to root_path, class: 'nav-link text-dark text-center bg-light' do
                  | タイムライン
                = link_to topics_path, class: 'nav-link text-dark text-center bg-light' do
                  | 掲示板
                = link_to users_path, class: 'nav-link text-dark text-center bg-light' do
                  | ランキング
            li.nav-item
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-light'
          .form-inline.ml-xl-auto.mr-xl-4.py-2
            = form_with url: search_path, method: :get, local: true do |f|
              .input-group
                .input-group-prepend
                  = f.select :model, options_for_select({ "ユーザー" => "user", "つぶやき" => "tweet" }), {}, class: 'btn btn-light border'
                = f.text_field :content, class: 'form-control border', placeholder: '検索'
                .input-group-append
                  = button_tag :type => "submit", :class =>"btn btn-dark" do
                    i.fa.fa-search
      - else
        .note.text-light.py-2.ml-xl-5.text-xl-center.text-start
          span
            | ログインもしくは新規登録が必要です。
        ul.navbar-nav.ml-xl-5.align-items-xl-center.align-items-start
          li.nav-item.mr-xl-4
            = link_to "ログイン", new_user_session_path, class: 'nav-link text-light'
          li.nav-item.mr-xl-4
            = link_to "新規登録", new_user_registration_path, class: 'nav-link text-light'
          li.nav-item
            = link_to "WeChangeとは？", about_path, class: 'nav-link text-light'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | WeChange
    = csrf_meta_tags
    = csp_meta_tag
    meta[name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"]
    script[src="https://kit.fontawesome.com/73c08f5520.js" crossorigin="anonymous"]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link[rel="preconnect" href="https://fonts.googleapis.com"]
    link[rel="preconnect" href="https://fonts.gstatic.com" crossorigin]
    link[href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&family=Roboto&display=swap" rel="stylesheet"]
  body.d-flex.flex-column.vh-100
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    main.py-lg-4.mb-auto
      = yield
    span#back
      a[href="#"]
        = image_tag 'arrow.png', width: '50px'
    = render 'layouts/footer'